export const data = [
  {
    name: "Bitcoin (BTC)",
    price: "$31,812.80",
    price_stat: "+10%",
    tvl: "$60,000",
    popular_pairs: ["SOL.png", "ETH.png", "BUSD.png"],
    logo: "BTC",
    no: 1,
  },
  {
    name: "Solana (SOL)",
    price: "$32.83",
    price_stat: "-12.32%",
    tvl: "$60,000",
    popular_pairs: ["BTC.png", "ETH.png", "BUSD.png"],
    logo: "SOL",
    no: 2,
  },
  {
    name: "Ethereum (ETH)",
    price: "$1,466.45",
    price_stat: "-11.93%",
    tvl: "$60,000",
    popular_pairs: ["SOL.png", "BTC.png", "BUSD.png"],
    logo: "ETH",
    no: 3,
  },
  {
    name: "Binance USD (BUSD)",
    price: "$1.00",
    price_stat: "+0.26%",
    tvl: "$60,000",
    popular_pairs: ["SOL.png", "ETH.png", "BUSD.png"],
    logo: "BUSD",
    no: 4,
  },
  {
    name: "Shiba Inu (SHIB)",
    price: "$0.00000001948",
    price_stat: "-8.1%",
    tvl: "$60,000",
    popular_pairs: ["SOL.png", "ETH.png", "BUSD.png"],
    logo: "SHIB",
    no: 5,
  },
];
